# Build status located at https://travis-ci.org/yuzu-emu/

language: node_js
node_js:
  - "11"
cache: yarn

install:
  - echo '========== Installing gulp & dependencies =========='
  - sudo apt-get install graphicsmagick
  - wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
  - yarn install

before_script:
  - hugo version

script:
  - echo '========== Starting gulp deploy task =========='
  - yarn run gulp all --production

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: build
 repo: yuzu-emu/yuzu-emu.github.io
 target_branch: master
 fqdn: yuzu-emu.org
 on:
   branch: hugo
notifications:
  email:
    - yuzu@yuzu-emu.org
