# Build status located at https://travis-ci.org/yuzu-emu/

language: node_js
node_js: node
cache: yarn

install:
  - echo '========== Installing gulp & dependencies =========='
  - sudo apt-get install graphicsmagick
  - wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
  - yarn global add gulp
  - yarn install

before_install:
  - hugo version

script:
  - echo '========== Starting gulp deploy task =========='
  - gulp all --production

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: build
 repo: yuzu-emu/yuzu-emu.github.io
 target_branch: master
 fqdn: yuzu-emu.org
 on:
   branch: hugo
notifications:
  email:
    - mods@citra-emu.org
