baseurl = "https://yuzu-emu.org/"
languageCode = "en-us"

DefaultContentLanguage = "en"
theme = "shared-bulma-theme"

# Define how many objects appear per pagination.
paginate = 10

[params]
  GithubURL = "https://github.com/yuzu-emu/yuzu"
  TwitterURL = "https://twitter.com/notfunnei"
  ProjectName = "yuzu Emulator Project"

[Languages]
  [Languages.en]
    title = "yuzu"
    tagline = "An experimental Nintendo Switch Emulator"
    description = "YuzuÂ is a highly experimental open-source emulator for the Nintendo Switch."
    weight = 1

[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML", "JSON" ]