baseurl = "https://yuzu-emu.org/"
languageCode = "en-us"

DefaultContentLanguage = "en"
theme = "shared-bulma-theme"

# Define how many objects appear per pagination.
paginate = 20

[[menu.main]]
  name = "blog"
  weight = 1
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "download"
  weight = 2
  identifier = "download"
  url = "/downloads"

[[menu.main]]
  name = "wiki"
  weight = 2
  identifier = "wiki"
  url = "/wiki/home/"

[[menu.main]]
  name = "donate"
  weight = 3
  identifier = "donate"
  url = "/donate"

[Params]
  BulmaPrimaryShade = "is-dark"
  DiscordURL = "https://discord.gg/u77vRWY"
  TwitterURL = "https://twitter.com/yuzuemu"
  GithubURL = "https://github.com/yuzu-emu/yuzu"
  GoogleAdsenseClient = "ca-pub-4126545610079023"
  GoogleAnalyticsTrackingId = "UA-112443698-1"

[Params.fmt]
  ISO8601 = "2006-01-02T15:04:05-07:00"
  Date = "January 02 2006"

[Languages]
  [Languages.en]
    title = "yuzu"
    tagline = "Nintendo Switch Emulator"
    description = "yuzuÂ is a highly experimental open-source emulator for the Nintendo Switch."
    weight = 1

[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML" ]
