baseurl = "https://yuzu-emu.org/"
languageCode = "en-us"

DefaultContentLanguage = "en"
theme = "shared-bulma-theme"

# Define how many objects appear per pagination.
paginate = 10

[[menu.main]]
  name = "about"
  weight = 1
  identifier = "about"
  url = "/"

[[menu.main]]
  name = "wiki"
  weight = 1
  identifier = "wiki"
  url = "/wiki/home/"


[[menu.main]]
  name = "donate"
  weight = 3
  identifier = "donate"
  url = "/donate"

[params]
  DiscordURL = "https://discord.gg/gz9pz97"
  TwitterURL = "https://twitter.com/yuzuemu"
  GithubURL = "https://github.com/yuzu-emu/yuzu"
  GoogleAdsenseClient = "ca-pub-4126545610079023"
  GoogleAdsenseSlot = "5525580072"

[Languages]
  [Languages.en]
    title = "yuzu"
    tagline = "An experimental emulator for the Nintendo Switch"
    description = "YuzuÂ is a highly experimental open-source emulator for the Nintendo Switch."
    weight = 1

[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML", "JSON" ]