name = "Shared Bulma Theme"
license = "AGPLv3"
licenselink = ""
description = "Shared Bulma Theme"
homepage = "https://citra-emu.org/"
tags = []
features = ["", ""]
min_version = 0.16

[author]
  name = "flamesage"