name: Deploy Site

on:
  push:
    branches: [ hugo ]
  pull_request:
    branches: [ hugo ]
  schedule:
    - cron: '25 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        echo '========== Installing gulp & dependencies =========='
        sudo apt-get install graphicsmagick
        yarn install
        # Install dependencies one-by-one to avoid race-conditions
        pushd ./scripts/shared-hugo-scripts/wiki/ && yarn && popd
        pushd ./scripts/shared-hugo-scripts/compatdb/ && yarn && popd
        yarn hugo version
    - name: Build
      env:
        GITHUB_WIKI_URL: 'https://github.com/yuzu-emu/yuzu.wiki.git'
        TENANT: 'yuzu'
      run: |
         echo '========== Starting gulp deploy task =========='
         yarn run build
    - name: Deploy
      if: ${{ ! github.base_ref }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: build
        CLEAN: true
        SINGLE_COMMIT: true
